import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'

//Components Import
import Navbar from './_component/Navbar'
import Footer from './_component/Footer'
import CircleMouseFollwer from "@/app/_component/CircleMouseFollower";
//
const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
      <CircleMouseFollwer />
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
